Fixes #2
timgthomas/vscode-toggle-explorer-gitignore pull request #3
Opened 2023-11-30 02:18 UTC by mikeburgh

Adds the icon to the tree view, not sure if the eye should be open when showing the files or closed, thoughts ?

Also added detecting if the config is changed manually. It's a bit redundant when it's changed via the commands as it sets context again, but without setting it via the commands there was a slight lag with the icon changing when clicking it.

2024-08-24 04:43 UTC, timgthomas commented
@mikeburgh, this is beyond amazing! Thank you for your contributions, and my sincerest apologies for the *ahem* months-long delay!

> not sure if the eye should be open when showing the files or closed, thoughts ?

Excellent pattern; I agree! Allow me a bit to review the change and poke around, but I'm loving your updates. Thanks again!

2024-08-24 05:43 UTC, timgthomas requested changes
These are great updates! I'm seeing something strange when testing locally; have you experienced this?

https://github.com/user-attachments/assets/2d11fe02-2429-4ee2-bb4c-b29f928cf1e2

I haven't done too much debugging yet, but I did see it working earlier! Aside from the above, one small nit, and this'll be good to go! 🙌

2024-08-24 05:43 UTC, timgthomas commented on extension.js
> +  let toggleCommand = registerCommand(`${namespace}.toggle`, (value) => {
Mind making a local copy of `value` to avoid modifying the parameter?

2024-09-06 04:26 UTC, timgthomas commented
Hope you don't mind, @mikeburgh, but my feedback was so minor and these are such good improvements, I wanted to get them in!

2024-09-06 04:26 UTC, timgthomas approved these changes

2024-09-06 04:28 UTC, merged

2024-09-09 00:58 UTC, mikeburgh commented
No worries at all, I was on the road so only just getting back to look at them now anyway.